#!/usr/bin/env bash
# This script modifies /etc/hosts so that localhost resolves to 127.0.0.2
# and facebook.com resolves to 8.8.8.8

cp /etc/hosts /etc/hosts.bak

# Remove all occurrences of 'localhost' and 'facebook.com' from /etc/hosts, even if they are on the same line
sed -i.bak '/localhost/d;/facebook.com/d' /etc/hosts
# Remove 'localhost' from any line where it appears as an alias
sed -i.bak 's/\(\s\|^\)localhost\(\s\|$\)//g' /etc/hosts

echo "127.0.0.2   localhost" >> /etc/hosts
echo "8.8.8.8     facebook.com" >> /etc/hosts